// F-001 pages: /privacy (public, in the sitemap, linked from the homepage privacy line) and /book
// (ships dark: noindex, not in the nav or sitemap). Both are generated by build.mjs from content.json.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { checkPage, checkHeaders, parseHtml } from "../build.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const read = (f) => readFileSync(join(ROOT, f), "utf8");
const content = JSON.parse(read("content.json"));

// Every element in a parsed page, hidden or not.
const all = (html) => {
  const out = [];
  (function walk(n) { for (const c of n.children ?? []) if (c.tag) { out.push(c); walk(c); } })(parseHtml(html));
  return out;
};
const textOf = (html) => html.replace(/<(script|style)[\s\S]*?<\/\1>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&#39;|&rsquo;/g, "'").replace(/\s+/g, " ");

// Anything that would make the browser fetch from another origin: a src, a stylesheet/icon/preload
// link, or a CSS url(). Canonical and alternate links are not requests.
function externalRequests(html) {
  const found = [];
  const offSite = (u) => !u.startsWith("/") || u.startsWith("//");
  for (const el of all(html)) {
    if (el.attrs.src !== undefined && offSite(el.attrs.src)) found.push(`<${el.tag} src=${el.attrs.src}>`);
    const rel = (el.attrs.rel ?? "").toLowerCase();
    if (el.tag === "link" && !/^(canonical|alternate)$/.test(rel) && offSite(el.attrs.href ?? "")) found.push(`<link rel=${rel} href=${el.attrs.href}>`);
    if (el.tag === "style") for (const m of el.raw.matchAll(/url\(\s*["']?([^"')]+)/g)) if (offSite(m[1])) found.push(`url(${m[1]})`);
    if (el.tag === "form" && el.attrs.action) found.push(`<form action=${el.attrs.action}>`);
  }
  return found;
}
const rulesFor = (headers, path) => headers.split("\n\n").map((b) => b.replace(/^(#.*\n)+/, "")).filter((b) => b.split("\n")[0] === path);

// ---- /privacy ----

test("/privacy is generated with its own title, description, canonical URL and one <h1>", () => {
  assert.ok(existsSync(join(ROOT, "public/privacy.html")), "public/privacy.html is missing");
  const html = read("public/privacy.html");
  assert.match(html, /<title>Privacy — Patrick Vieira<\/title>/);
  assert.match(html, /<meta name="description" content="[^"]{20,}">/);
  assert.match(html, /<link rel="canonical" href="https:\/\/patrickjv\.com\/privacy">/);
  assert.equal(all(html).filter((e) => e.tag === "h1").length, 1);
  assert.doesNotMatch(html, /noindex/);
});

test("/privacy says what is stored, for how long, and who processes it", () => {
  const text = textOf(read("public/privacy.html"));
  for (const must of [/introductions?/i, /book/i, /30 days after the meeting/, /hold/, /hash/i, /Google/, /Resend/, /Cloudflare/, /free or busy|free\/busy/i, /no cookies/i, /no analytics/i, /hello@patrickjv\.com/])
    assert.match(text, must);
});

test("/privacy is in the sitemap and has exactly one CSP rule per path", () => {
  assert.match(read("public/sitemap.xml"), /<loc>https:\/\/patrickjv\.com\/privacy<\/loc>/);
  const headers = read("public/_headers");
  assert.deepEqual(checkHeaders(headers), []);
  for (const p of ["/privacy", "/privacy.html"]) {
    const rules = rulesFor(headers, p);
    assert.equal(rules.length, 1, `one rule for ${p}`);
    assert.match(rules[0], /Content-Security-Policy: default-src 'none'.*frame-ancestors 'none'/);
  }
});

test("the homepage privacy line links to /privacy, and removing that link fails the page check", () => {
  const page = read("public/index.html");
  const els = all(page);
  const line = els.find((e) => e.tag === "p" && /(^|\s)privacy(\s|$)/.test(e.attrs.class ?? ""));
  assert.ok(line, "no privacy line");
  assert.ok(els.some((e) => e.tag === "a" && e.attrs.href === "/privacy" && e.parent === line), "privacy line has no link to /privacy");
  assert.deepEqual(checkPage(page, content), []);
  const unlinked = page.replace(/<a href="\/privacy">([^<]*)<\/a>/, "$1");
  assert.notEqual(unlinked, page);
  assert.ok(checkPage(unlinked, content).length > 0, "the page check did not notice the missing link");
});

test("/privacy makes no request to another origin and runs no script", () => {
  const html = read("public/privacy.html");
  assert.deepEqual(externalRequests(html), []);
  assert.equal(all(html).filter((e) => e.tag === "script" && e.attrs.type !== "application/ld+json").length, 0);
});

// ---- /book (ships dark) ----

test("/book is generated, noindex, with its own title and one <h1>", () => {
  assert.ok(existsSync(join(ROOT, "public/book.html")), "public/book.html is missing");
  const html = read("public/book.html");
  assert.match(html, /<title>Book a meeting — Patrick Vieira<\/title>/);
  assert.match(html, /<meta name="robots" content="noindex">/);
  assert.equal(all(html).filter((e) => e.tag === "h1").length, 1);
});

test("/book ships dark: not in the sitemap, the homepage, index.md or llms.txt", () => {
  assert.doesNotMatch(read("public/sitemap.xml"), /\/book/);
  for (const f of ["public/index.html", "public/writing/index.html", "public/privacy.html"])
    assert.ok(!all(read(f)).some((e) => e.tag === "a" && /^(https:\/\/patrickjv\.com)?\/book/.test(e.attrs.href ?? "")), `${f} links to /book`);
  for (const f of ["public/index.md", "public/llms.txt"]) assert.doesNotMatch(read(f), /patrickjv\.com\/book/, f);
});

test("/book has exactly one CSP rule per path and makes no request to another origin", () => {
  const headers = read("public/_headers");
  assert.deepEqual(checkHeaders(headers), []);
  for (const p of ["/book", "/book.html"]) {
    const rules = rulesFor(headers, p);
    assert.equal(rules.length, 1, `one rule for ${p}`);
    assert.match(rules[0], /Content-Security-Policy: default-src 'none'.*frame-ancestors 'none'/);
  }
  assert.deepEqual(externalRequests(read("public/book.html")), []);
});

test("/book form: native controls, every field labelled, a polite live status region", () => {
  const els = all(read("public/book.html"));
  const ids = new Set(els.filter((e) => e.tag === "label").map((e) => e.attrs.for));
  for (const id of ["name", "email", "note"]) {
    assert.ok(els.some((e) => e.attrs.id === id && /^(input|textarea)$/.test(e.tag)), `no #${id} field`);
    assert.ok(ids.has(id), `#${id} has no <label for>`);
  }
  assert.equal(els.find((e) => e.attrs.id === "email").attrs.type, "email");
  assert.equal(els.find((e) => e.attrs.id === "note").attrs.maxlength, "500");
  for (const id of ["types", "days", "times"]) {
    const box = els.find((e) => e.attrs.id === id);
    assert.ok(box, `no #${id}`);
    let n = box.parent; while (n && n.tag !== "fieldset") n = n.parent;
    assert.ok(n && n.children.some((c) => c.tag === "legend"), `#${id} is not inside a fieldset with a legend`);
  }
  const status = els.find((e) => e.attrs.id === "status");
  assert.equal(status?.attrs["aria-live"], "polite");
  assert.ok(els.some((e) => e.tag === "button" && e.attrs.type === "submit"));
});
